In [1]:
import tensorflow as tf
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:
myconst = tf.constant([7,2], name="myconst")

In [3]:
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "myconst"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\007\000\000\000\002\000\000\000"
      }
    }
  }
}
versions {
  producer: 38
}



In [6]:
x = tf.placeholder(tf.float32 , shape=(1024,1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
    rand_array = np.random.rand(1024,1024)
    print(sess.run(y, feed_dict={x: rand_array}))

[[244.42972 254.65027 248.6838  ... 249.08342 254.07578 245.4163 ]
 [270.69647 274.91827 270.60675 ... 267.13672 271.7713  263.2249 ]
 [253.4049  257.49423 246.90489 ... 256.952   258.7297  248.0328 ]
 ...
 [249.92754 259.67755 251.8172  ... 253.20966 258.7357  254.08295]
 [251.9165  262.4098  251.12453 ... 252.99915 256.18665 251.23106]
 [257.4267  266.55188 257.88947 ... 257.53064 261.73438 254.15594]]


In [8]:
img = [1,2,3,4,5]
label = [10, 20, 30, 40, 50]

ph_img = tf.placeholder(dtype=tf.float32)
ph_lb = tf.placeholder(dtype=tf.float32)

total = ph_img + ph_lb
with tf.Session() as sess:
    result = sess.run(total, feed_dict={ph_img:img, ph_lb:label})
    print(result)

[11. 22. 33. 44. 55.]


In [9]:
#두 값을 입력받아 최대를 구하는 프로그램.
n1 = tf.placeholder(tf.int32)
n2 = tf.placeholder(tf.int32)
max = tf.maximum(n1, n2)

with tf.Session() as sess:
    str = input("두 정수를 공백으로 분리하여 입력하세요. ")
    values = str.split()
    x1 = values[0]
    x2 = values[1]
    result = sess.run(max, feed_dict={n1: x1, n2:x2})
    print(result)

두 정수를 공백으로 분리하여 입력하세요. 5 3
5


In [22]:
#성적 리스트의 평균과 최대값, 최소값을 출력하는 프로그램

sum = tf.Variable(0)
max = tf.Variable(0)
min = tf.Variable(100)
n = tf.placeholder(tf.int32)

summing = sum.assign_add(n)
min_op = tf.cond( tf.less(min, n), lambda:min.assign(min), lambda:min.assign(n) )
max_op = tf.cond( tf.less(max, n), lambda:max.assign(n), lambda:max.assign(max))
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    str = input("성적을 공백으로 분리하여 입력하세요. ")
    values = str.split()
    for i in values:
        sess.run([summing,min_op,max_op], feed_dict={n : i})
    print(sum.eval())
    print(min.eval())
    print(max.eval())

성적을 공백으로 분리하여 입력하세요. 5 3 2 10
20
2
10
